pgactivity/UI.py
psutil 2.1.1 is warning about deprecated functions get_memory_percent() and get_cpu_percent() in the header of the UI. This simply calls the functions as suggested by the warning.
=> Deprecation warnings from psutil

pg_activity, pgactivity/Data.py
Taken from the following blog post and fork:
http://blog.geesu.net/2015/06/09/using-pg_activity-with-amazon-rds/
https://github.com/Geesu/pg_activity/tree/feature/amazon-rds
Just adds this as an command line option instead of forcing it on all users.  Should maintain backwards compatibility with the previous functionality, just allows this to be used without errors when running against a remote RDS database.  All credit should go to @Geesu as he was the person that did the original legwork.
I can add documentation if you want, but I kept it minimal for now incase you would prefer a different approach to solving this problem.
=> Adds support for using pg_activity with Amazon RDS

docs/man/pg_activity.1, docs/man/pg_activity.pod
Update manpage's NAME section so that tools such as whatis(1) or apropos(1) could use it
=> Manpage fixes

pgactivity/UI.py
We use barman with wal shipping for PITR on our main database. This creates a
walsender process that is not connected to any specific database.
=> process['database'] can be None for some maintenance processes

docs/man/pg_activity.1, docs/man/pg_activity.pod
Added a sentence in the man page for people like me that didn't read the README on github and didn't know that pg_activity could show system information, provided it runs as the right user.
Added an example, and updated the one with `-h /tmp` (not used anymore on Debian and RH since 9.4 at least).
I suppose that I had to run build-man.sh.
=> Doc update about system info + examples

README.md, pg_activity, pgactivity/Data.py
On clusters with thousands of databases, computing
total size of the cluster is painfull and make
pg_activity unusable. Don't compute the value make
pg_activity usable on those large clusters.
=> [IMP] new option to avoid total db sizes

README.md, docs/man/pg_activity.1, docs/man/pg_activity.pod, pg_activity, pgactivity/UI.py
This new option defines a file path where to store running
queries/backends using CSV format. Default value is None, meaning the
feature is not active.
Running queries storage is working when pg_activity is on RUNNING
QUERIES tab only.
Fix #62
=> Add --output option

.gitignore, README.md, docs/man/pg_activity.1, docs/man/pg_activity.pod, pg_activity, pgactivity/Data.py, pgactivity/UI.py
764/5000
Hello Lulien. I really loved the option --no-dbsize. It's something I was already thinking of implementing because I was having load problems due to the high cost of the query. Since its availability, I have always used it, but many times I have wanted to see what the current size of the base is. I needed to run another instance of pg_activity without the --no-dbsize option only to see the size of the base and just after closing it. I then created an interactive option for this, using the "D" to signal the refresh. I'm not a python programmer, so I don't know if I did it the best way. Feel free to perform any refactorings you deem appropriate. Thank you in advance for accepting my pull request. It's really very enjoyable for me to contribute to this very cool project.
=> Adding refresh dbsize interative action

pg_activity
If exception occurs during the connection to the database we refer to `debug` variable which is not defined yet. So we should define it before we connect to the database. Error message I got before fixing the issue:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/pg_activity-1.5.0-py3.7.egg/EGG-INFO/scripts/pg_activity", line 254, in main
File "/usr/local/lib/python3.7/site-packages/pg_activity-1.5.0-py3.7.egg/EGG-INFO/scripts/pg_activity", line 417, in pg_connect
File "/usr/local/lib/python3.7/site-packages/pg_activity-1.5.0-py3.7.egg/pgactivity/Data.py", line 165, in pg_connect
Exception: Must be run with database superuser privileges.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```
=> Fix issue with undefined `debug` variable

AUTHORS.md, README.md, docs/man/pg_activity.1, docs/man/pg_activity.pod, pg_activity, pgactivity/Data.py, pgactivity/UI.py
- so far the content of the TIME column only reflected the duration of the query
- this PR introduces 2 other duration modes: transaction, backend
- press T to cycle through different duration modes
- active duration mode is shown in the top status bar:
=> Introduce an explicit "duration mode"

pgactivity/Data.py, pgactivity/UI.py
* This commit attempts to solve the issue : #130 [1].
* PoWA has a bug where `backend_type` is not correctly filled [2]. it
was fixed but it's not in the stable version yet.
* Since [3], we queried for the `backend_type` and filtered
`parallel workers` in the Python code. The test is now done in
SQL,  which avoids the problems all together.
* The `parallel worker` detection was not working for pg 11+ because
it uses the 'parallel worker' backend_type. It's now fixed.
[1] https://github.com/dalibo/pg_activity/issues/130
[2] https://github.com/powa-team/powa-archivist/pull/20
[3] https://github.com/dalibo/pg_activity/commit/6a180d86139d68a728946997996f346cc880888e
=> Replace backend_type with is_background_worker

pg_activity
This is a proposition for the release notes :                                             
Change log:                                                                     
* Add the --min-duration flag to only show laggy queries (@kmoppel)             
* Add the --duration-mode and the shortcut (T) to choose the duration modes:       
query, transaction, backend (@nilshamerlinck )                                
* Move to dalibo labs (@daamien)                                                
* Expand current 1-3s refresh interval to 0.5-5s (@kmoppel)                     
* Add the refresh dbsize interative action (D) (Fabio Renato Geiss)             
* Add --verbose-mode in man page (@julmon)                                      
Bug fixes: …
=> Bump version to 1.6.0

pgactivity/Data.py
The state column appeared in PG 9.2 along with the change "current_query" => "query".
Before the current_query column contained the following for non active queries :
* `<IDLE> in transaction (aborted)`
* `<IDLE> in transaction`
* `<IDLE>`
=> Fix the display of the state of transaction for PostgreSQL < 9.1

README.md, pg_activity, pgactivity/compat.py, pgactivity/views.py, tests/test_ui.txt
* first commit drops `--debug` flag which is no longer handled
* second commit fixes a compatibility issue with old versions of blessed, as available in debian stable
=> compat with old blessed

pg_activity, pgactivity/data.py, pgactivity/types.py, pgactivity/ui.py, pgactivity/views.py, tests/test_ui.txt, tests/test_views.txt
Add connection strings to address https://github.com/dalibo/pg_activity/issues/151 & https://github.com/dalibo/pg_activity/issues/147
The idea is to mimic psql behavior of allowing a connection string to be specified as argument of the script. In that case the information provided overrides the host, port, user and dbname options.
Two syntax are possible  (depending in the version of libpq). (https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING)
```
pg_activity "host=/tmp port=5432 user=toto dbname=pgbench"
pg_activity "postgresql://toto@localhost:5432/bench"
```
I am not very fond of the argument thing, I would have preferred an option like --dsn or somehing. It's less ugly in my pov but it's done like that in psql.
Note: I also fixed the default value of dbname …
=> Connection string

pg_activity, pgactivity/types.py
Follow-up on https://github.com/dalibo/pg_activity/pull/156#issuecomment-754658744, @blogh. 
The UI behaves slightly differently as it would now display the socket value (e.g. `/var/run/postgresql`) instead of `localhost` in the header line for local connection.
=> Use conninfo to populate the Host value

pgactivity/data.py
=> Fix query name for 'get_active_connections'

pg_activity, pgactivity/__main__.py, pgactivity/cli.py, pgactivity/data.py, pyproject.toml, setup.py, tox.ini
Also add the possiblity to run the program as `python -m pgactivity <options>`.
Also remove the copyright/license notice on top of some files, as it's already stated in license.txt file.
Fix #197.
Fix #196.
=> ship the console script as a setuptools entry point

pgactivity/activities.py, pgactivity/queries/get_pg_activity_post_100000.sql, pgactivity/queries/get_pg_activity_post_110000.sql, pgactivity/queries/get_pg_activity_post_90600.sql, pgactivity/types.py, pgactivity/utils.py, tests/data/local-processes-input.json, tests/test_views.txt
* Before postgres 9.6, there's no `wait_event` nor `wait_event_type` column
* In postgres 9.6, `wait_event_type` values can be `LWLockNamed`, `LWLockTranche`, `Lock`, `BufferPin` and `wait_event` column is available.
* In postgres 10, new `wait_event_type` values: Activity, Extension, Client, IPC, Timeout, IO and many new `wait_event` (literal) values available.
Currently, in pg_activity:
*  prior to postgres 9.6, we simply use the `wait` (boolean) column of pg_stat_activity
* in postgres 9.6, we define the query as waiting if `wait_event IS NOT NULL`
* from version 10, we define the query as waiting when ` wait_event_type IN ('LWLock', 'Lock', 'BufferPin')`
(This seems inconsistent to me.)
Always use `wait_event` when available and, if not NULL, declare the query as "waiting".
(See …
=> Display pg_stat_activity's wait_event when available

pgactivity/views.py
This apparently poses problem for some terminals
(https://github.com/dalibo/pg_activity/issues/208) and we, in fact, do
not need a sequence-aware text wrapper here, since the query string
contains no escape sequence, but only text.
=> Do not use blessed's text wrapper for the query string

pgactivity/views.py, tests/test_ui.txt, tests/test_views.txt
We rework the header view in order to make the rendering more compact,
by limiting the amount of white spaces between columns, and to make the
columns / rows data more extensible.
Now the header() view displays two blocks:
* first row (containing "Size", "Active connections", "Duration mode"
information) is always visible and has its own alignment
* subsequent rows, only available in local mode and displaying extra
system information, also use their own alignment
In the first block, we change the | column delimiter into a blue ⋅. In
the second one, we use a comma (similarly to what top uses).
Besides, columns no longer have a fixed width, thus make the rendering
more compact.
Adding extra columns should be simpler now, thus preparing work for #213.
=> Overhaul the header view

docs/man/pg_activity.1, docs/man/pg_activity.pod, pgactivity/activities.py, pgactivity/data.py, pgactivity/queries/get_blocking.sql, pgactivity/queries/get_blocking_post_90600.sql, pgactivity/types.py, tests/test_data.py, tests/test_views.txt
Blocking queries can be long for a number of reasons, the wait_event
column of pg_activity can help us understand them. Therefore, it was
added to the blocking query panel.
=> Add a waitevent column to blocking queries

tests/conftest.py
Some tests require to run queries outside of a transaction block.
eg: CREATE INDEX CONCURRENTLY
This is necessary to add tests to #224.
=> add autocommit option to the execute function of the tests

setup.py
We now always set the data_files option to setuptools.setup() call
making the man page be installed. This will work when installing with
pip, but not with 'python setup.py install'. At least people using pip
will now get the man page.
=> Let the man page be installed by pip

pgactivity/queries/get_blocking.sql, pgactivity/queries/get_blocking_post_90200.sql, pgactivity/queries/get_blocking_post_90600.sql
I had a long running transaction which blocked a repack process. I realized that pg_activity couldn't display which ended up with this patch. 
I could only test get_blocking_post_90600.sql since I don't have any old environment.
=> Blocking query now lists transactions which blocks virtualxid.

pgactivity/data.py
We convert the timestamp difference into a float, as it appears to be a
Decimal in some cases. Then converting size_ev into a float is no longer
needed.
Fixes #233.
=> Fix a possibly TypeError when computing size growth

.github/workflows/tests.yml, pgactivity/queries/get_blocking.sql, pgactivity/queries/get_blocking_post_90200.sql, pgactivity/queries/get_blocking_post_90600.sql, pgactivity/queries/get_pg_activity.sql, pgactivity/queries/get_pg_activity_post_100000.sql, pgactivity/queries/get_pg_activity_post_110000.sql, pgactivity/queries/get_pg_activity_post_90200.sql, pgactivity/queries/get_pg_activity_post_90600.sql, pgactivity/queries/get_waiting.sql, pgactivity/queries/get_waiting_post_90200.sql, tests/conftest.py, tests/test_data.py
When the encoding of a database is not UTF8. Queries with special
caracters might crash pg_activity with the message :
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 26:
++  invalid continuation byte
This patch fixes the issue by querying pg_database.encoding and using it
to encode the string.
=> Fix encoding errors #149 > still WIP

pgactivity/data.py
Instead of formatting query string with the duration_column value
ourselves, we use psycopg2's string composition helpers which should be
safer: https://www.psycopg.org/docs/sql.html
=> Use psycopg2 SQL string composition

setup.py
Should fix test failures in #252.
=> Use pytest-postgresql ~= 3.0

README.md
How to pass the password to the PSQL connection is not obvious from the current documentation. 
Add a basic example with links to the more documentation.
=> Document authentication

pgactivity/queries/get_pg_activity_post_100000.sql, pgactivity/queries/get_pg_activity_post_90200.sql, pgactivity/queries/get_pg_activity_post_90600.sql
This prevents an ambiguous column identifier error.
=> Add missing colum qualifier for dbname

pgactivity/types.py, pgactivity/views.py, tests/test_ui.txt, tests/test_views.py, tests/test_views.txt
=> UI refactorings

pgactivity/views.py, tests/test_scroll.txt, tests/test_ui.txt
This is an alternative proposal to #257 which (in my opinion) produces a less strange behavior.
When scrolling through processes and the query is wrapped, there is no
way to compute an offset for the table rows in order to move the cursor.
Instead, when query is wrapped, we now always display focused process on
top of the table and we wrap around the processes list (display first
processes at the end of the table).
@blogh, what do you think?
=> Keep focused line on top of processes table when query is wrapped

pgactivity/views.py
This fixes up commit d8d54b2c8301afb39e39282642a8259d97e20abd which made
the UI crash when there was no horizontal space to display the query
column on the processes table. Now we don't display that column if it's
outside screen.
=> Do not display (nor wrap) the query when the column is not visible

README.md
1) Installation instructions of the dev version for people with low python skills, like me (thanks @blogh).
2) I've added the name of the packages from the PGDG. The one from Debian is not so obvious.
=> README.md: howto execute development versions for non-devs

setup.py
We use precisedelta() introduced in that version.
=> Require humanize >= 2.6.0

pgactivity/data.py
Using old v11 SQL causes "permission denied for function pg_ls_dir" errors on managed Azure instances
```
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/krlc/git/postgres/pg_activity/pgactivity/__main__.py", line 4, in <module>
main()
File "/home/krlc/git/postgres/pg_activity/pgactivity/cli.py", line 327, in main
ui.main(term, dataobj, host, args)
File "/home/krlc/git/postgres/pg_activity/pgactivity/ui.py", line 29, in main
server_information = data.pg_get_server_information(
File "/home/krlc/git/postgres/pg_activity/pgactivity/data.py", line 225, in pg_get_server_information
cur.execute(
File …
```
=> Activate the correct get_server_info SQL for v12/13

pgactivity/queries/get_blocking_oldest.sql, pgactivity/queries/get_blocking_post_090200.sql, pgactivity/queries/get_blocking_post_090600.sql, pgactivity/queries/get_pg_activity_oldest.sql, pgactivity/queries/get_pg_activity_post_090200.sql, pgactivity/queries/get_pg_activity_post_090600.sql, pgactivity/queries/get_pg_activity_post_100000.sql, pgactivity/queries/get_pg_activity_post_110000.sql, pgactivity/queries/get_waiting_oldest.sql, pgactivity/queries/get_waiting_post_090200.sql
pg_activity crashes when queries use newlines or regexp as show in
issue https://github.com/dalibo/pg_activity/issues/275
This fix replaces single \ characters with double \ in the blocking,
waiting and activity queries.
=> Fix InvalidTextRepresentation

.gitignore
Running `tox -p` command produced these supposed to be ignored folders:
pgactivity/queries/__pycache__/
tests/__pycache__/
We also sort the ignored list in .gitignore.
=> Ignore all __pycache__ folders

pgactivity/activities.py
Currently they're jumping around annoyingly. Relevant for vers >= 9.6
where parallel query was added
=> Fix parallel workers under the lead process in the GUI

pgactivity/data.py, pgactivity/queries/get_data_directory.sql, pgactivity/queries/get_pid_file.sql
This patch adds hint messages to give feedback to the user when a
feature is disabled. Namely :
* tempfile (disabled because of privileges or timeout)
* wal receiver (disabled on Aurora because the feature not available)
* system counters (disabled because of lack of privilege, feature unavailable
on Mac, access to the pid file)
=> Add hint messages when features are disabled.

pgactivity/activities.py, pgactivity/data.py, pgactivity/queries/get_pg_activity_oldest.sql, pgactivity/queries/get_pg_activity_post_090200.sql, pgactivity/queries/get_pg_activity_post_100000.sql, pgactivity/queries/get_pg_activity_post_110000.sql, pgactivity/queries/get_pg_activity_post_130000.sql, pgactivity/types.py, tests/data/local-processes-input.json, tests/test_scroll.txt, tests/test_views.txt
We now sort by `query_leader_pid` ASC, `is_parallel_worker` ASC in
addition to `duration` DESC.
`query_leader_pid` is a crafted column:
* pre pg13, it's always `NULL`, the tuple order will still depend on the
order in witch the tuple are fetched;
* for pg13 and after, it's equal to `coaelesce(leader_pid, pid)` which
should fix the display.
Fix some tests which displayed different queries for a leader and it's
worker processes.
closes #297
=> Fix the parallel worker position in duration sort mode

pgactivity/types.py, tests/test_views.txt
In cases where there is no swap we don't display a percentage. The case with zero memory is also covered event if it's not realistic it doesn't cost much to do it.
Closes #318
=> Fix the case where there is no swap

.flake8
This backwards incompatible change was made in version 6.0.0 of flake8.
* Produce an error when invalid codes are specified in configuration (See also #1689, #1713).
see: https://github.com/pycqa/flake8/issues/1689#issuecomment-1326319235
=> Fix .flake8 for fake8 6.0.0

pgactivity/types.py
Mypy (many versions) raises a wrong error for Python 3.11:
pgactivity/types.py:888: error: Returning Any from function declared to return "str"  [no-any-return]
Should be fixed by commit:
https://github.com/python/mypy/commit/05a3f7d8d61bc298809e5363d3a23aa16fe776d2
=> Work around a mypy bug with Python 3.11

tests/test_data.py
This test will ensure we still to handle queries without throwing this exception :
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type bytea
=> Add test for #275

CHANGELOG.md, RELEASE.md
In #337, following #338, I added an `**Unreleased**` section in `CHANGELOG.md` following recommendations from https://keepachangelog.com/en/1.0.0/. So I am here adjusting the release how to explaining how to proceed about this.
=> complement release how-to about changelog

pgactivity/data.py, pgactivity/pg.py
More specifically, when running with psycopg (not psycopg2), we use the row_factory feature to move results row type casting in fetch*() methods. A compatibility layer is maintained for psycopg2, reproducing the previous code.
=> Use psycopg row factories

CHANGELOG.md, pgactivity/cli.py
Otherwise, it defaults to None, which is not handled by psycopg 3+ (in contrast with psycopg2).
Closes #346
=> Use an empty string as default connection_string

CHANGELOG.md, pgactivity/utils.py, setup.py
This mostly affects how the uptime time delta is rendered, i.e. instead of getting something like '5 days, 4 hours and 13 minutes', we get '5 days, 4:13:00' when humanize.precisedelta() is not available and our compatibility layer is used.
=> Add compatibility with old humanize

.github/workflows/tests.yml, CHANGELOG.md, pgactivity/data.py, pgactivity/pg.py, pgactivity/types.py, tests/conftest.py, tests/test_data.py
Addresses second part of #348.
=> convert postgres encoding to python ones

pgactivity/compat.py, pgactivity/data.py, pgactivity/utils.py, pgactivity/views.py
Result from running 'pyupgrade --py37-plus'.
Note: we don't run this by default in tox or CI because there's no way to configure this tool; so this is just a one-shot.
=> Upgrade Python syntax thanks to pyupgrade

CHANGELOG.md, pgactivity/views.py, tests/test_ui.txt, tests/test_views.txt
The character we were previously using, U+22C5 DOT OPERATOR, is apparently not rendering well for everybody. Let's use a plain ASCII character instead.
Fix #356
Fix #230
=> Delimit header columns with a comma instead of a dot

CHANGELOG.md, pgactivity/pg.py
Resolves the following error, that occurs if the connection is lost (e.g. server shutdown):
server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File ".../src/pg_activity/.venv/bin/pg_activity", line 8, in <module>
sys.exit(main())
File ".../src/pg_activity/pgactivity/cli.py", line 416, in main
newdataobj = dataobj.try_reconnect()
File ".../src/pg_activity/pgactivity/data.py", line 122, in try_reconnect
pg_conn = pg.connect(**self.dsn_parameters)
TypeError: connect() missing 1 required positional argument: 'dsn'
The 'dsn' argument of pg.connect() was incorrectly required.
=> Fix a type error upon reconnect

CHANGELOG.md, pgactivity/activities.py, pgactivity/queries/get_blocking_oldest.sql, pgactivity/queries/get_blocking_post_090200.sql, pgactivity/queries/get_blocking_post_090600.sql, pgactivity/queries/get_pg_activity_oldest.sql, pgactivity/queries/get_pg_activity_post_090200.sql, pgactivity/queries/get_pg_activity_post_090600.sql, pgactivity/queries/get_pg_activity_post_100000.sql, pgactivity/queries/get_pg_activity_post_110000.sql, pgactivity/queries/get_pg_activity_post_130000.sql, pgactivity/queries/get_waiting_oldest.sql, pgactivity/queries/get_waiting_post_090200.sql, pgactivity/types.py, tests/data/local-processes-input.json, tests/test_scroll.txt, tests/test_ui.txt, tests/test_views.txt
Instead of casting the client_addr to TEXT in PostgreSQL we keep the inet value which will be handled fine by psycopg. This brings us a nicer representation of some values, e.g. from 192.168.1.5/32 previously to 192.168.1.5. This will also help for IPv6 addresses which, if shortened that way, might fit better within the max width of the "client" column.
This is an alternative solution towards fixing #365, but not a complete solution as the column width is still limited to 16.
=> Preserve the 'inet' type of client_addr column

README.md
This is probably better than the previous 'pip install' instruction, as it manages a dedicated virtualenv, but pipx is not available anywhere so we have to keep both methods.
Rename the section into something more accurate.
=> Document installation with pipx

mypy.ini
The humanize library has type hints since version 4.2.0.
=> Drop now unneeded mypy ignore for 'humanize'

CHANGELOG.md, pgactivity/cli.py, pgactivity/data.py
This avoids showing a traceback to the user. To do so, we simply let the OperationalError propagate from data.pg_connect(), eventually catch it in cli.main() and exit with a nice error message.
Before:
```
$ pg_activity
Traceback (most recent call last):
File "/home/denis/src/pg_activity/pgactivity/data.py", line 517, in pg_connect
data = Data.pg_connect(
^^^^^^^^^^^^^^^^
File "/home/denis/src/pg_activity/pgactivity/data.py", line 93, in pg_connect
pg_conn = pg.connect(
^^^^^^^^^^^
File "/home/denis/src/pg_activity/pgactivity/pg.py", line 59, in connect
conn = psycopg.connect(dsn, autocommit=True, row_factory=dict_row, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/denis/src/pg_activity/.venv/lib/python3.11/site-packages/psycopg/connection.py", …
```
=> Catch connection error from the CLI entry point

.github/workflows/tests.yml, .pre-commit-config.yaml, CHANGELOG.md, README.md, pgactivity/compat.py, pgactivity/types.py, pyproject.toml, tox.ini
This version has reached its end-of-life last year, https://peps.python.org/pep-0537/#lifespan.
=> Drop support for Python 3.7

.github/workflows/tests.yml, .pre-commit-config.yaml, CHANGELOG.md, README.md, docs/man/pg_activity.1, docs/man/pg_activity.pod, pgactivity/activities.py, pgactivity/cli.py, pgactivity/compat.py, pgactivity/config.py, pgactivity/data.py, pgactivity/handlers.py, pgactivity/keys.py, pgactivity/pg.py, pgactivity/types.py, pgactivity/ui.py, pgactivity/utils.py, pgactivity/views.py, pgactivity/widgets.py, pyproject.toml, tests/conftest.py, tests/test_config.py, tests/test_data.py, tests/test_ui.txt, tests/test_views.txt, tox.ini
This stems from the idea discussed at https://github.com/dalibo/pg_activity/pull/387#issuecomment-1623178466.#396.
```
$ cat ~/.config/pg_activity/my.conf 
[database]
hidden = true
```
```
$ pg_activity --profile my  # will use the file above as configuration
```
One thing I wonder is whether the option should be named `--config <full-path-to-config>` or if we should introduce another option later on.
* * *
Based on #404
=> Add support for configuration profiles

.github/workflows/tests.yml, .pre-commit-config.yaml, CHANGELOG.md, README.md, docs/man/pg_activity.1, docs/man/pg_activity.pod, pgactivity/activities.py, pgactivity/cli.py, pgactivity/compat.py, pgactivity/config.py, pgactivity/data.py, pgactivity/handlers.py, pgactivity/keys.py, pgactivity/pg.py, pgactivity/types.py, pgactivity/ui.py, pgactivity/utils.py, pgactivity/views.py, pgactivity/widgets.py, pyproject.toml, tests/conftest.py, tests/test_config.py, tests/test_data.py, tests/test_ui.txt, tests/test_views.txt, tox.ini
based on #405 and #406; only last tree commits are new.
=> make it possible to control header items display from configuration file

CHANGELOG.md, pyproject.toml
Fix #411 
@asarubbo, can you check if this resolves #411 on Gentoo?
@mikelolasagasti, can you check if this change works for Fedora, as this reverts the one from #378?
=> Enable back setuptools automatic discovery

CHANGELOG.md, README.md, docs/man/pg_activity.1, docs/man/pg_activity.pod, pgactivity/cli.py, pgactivity/config.py, tests/test_cli.py, tests/test_cli_help.txt, tests/test_cli_help_py38.txt, tests/test_config.py, tests/test_ui.txt
=> Add non-negative counterparts of --no-XXX options

CHANGELOG.md, pgactivity/utils.py
Hello,
A client saw a problem with datetimeutc field using `pg_activity --output`. Here is a fix.
Instead of minutes, month was displayed.
Closes #430
Regards,
=> Fix bad date format for datetimeutc field

pyproject.toml
We are apparently affected by this issue:
https://github.com/python-humanize/humanize/issues/239
Let's avoid that version and wait for a fix.
=> Avoid humanize 4.12.0

CHANGELOG.md, docs/man/pg_activity.1, docs/man/pg_activity.pod, pgactivity/activities.py, pgactivity/cli.py, pgactivity/config.py, pgactivity/profiles/minimal.conf, pgactivity/profiles/narrow.conf, pgactivity/profiles/wide.conf, pgactivity/queries/get_pg_activity_oldest.sql, pgactivity/queries/get_pg_activity_post_090400.sql, pgactivity/queries/get_pg_activity_post_090600.sql, pgactivity/queries/get_pg_activity_post_100000.sql, pgactivity/queries/get_pg_activity_post_110000.sql, pgactivity/queries/get_pg_activity_post_130000.sql, pgactivity/types.py, pgactivity/utils.py, tests/data/local-processes-input.json, tests/test_cli.py, tests/test_cli_help.txt, tests/test_cli_help_py312.txt, tests/test_config.py, tests/test_scroll.txt, tests/test_ui.txt, tests/test_views.txt
The xmin horizon was added in 9.4 in commit [1], the addition of the column was asked in #425.
[1] https://github.com/postgres/postgres/commit/dd1a3bccca241a998b4ebf39d67202698e5fa599
=> Add the xmin horizon to running query display

CHANGELOG.md, pgactivity/data.py, pgactivity/queries/disable_log_statement.sql
We only disable log_min_duration_statement and log_min_duration_sample. when --hide-queries-in-logs which leaves us with tracs from log_statements. This aptch fixes that.
Authored by Kouber Saparev
=> Disable log_statements when --hide-queries-in-logs is used

CHANGELOG.md, pgactivity/queries/__init__.py
This avoids "polluting" server logs.
A doctest for queries.get() is added along the way.
Fix #442.
=> Strip commented and empty lines from SQL queries
