dalibo/pg_activity

- pgactivity/Data.py
Reflecting changes in pg_stat_activity.
Closes julmon/pg_activity#53
> Compatibility with Postgresql >= 9.6

- pg_activity
- pgactivity/Data.py
Don't do anything to get the password from the PGPASSFILE.
Psycopg2 uses libpq which does all the password handling correctly.
Addresses issue #51
> Depend on psycopg2 behaviour for passwords

- README.md
- docs/man/pg_activity.1
- docs/man/pg_activity.pod
As said in the title, it fixes minor typos.
> Fix various typos

- pgactivity/Data.py
- pgactivity/Process.py
- pgactivity/UI.py
> add 'state' column in all views

- pgactivity/Data.py
- pgactivity/UI.py
Added option in interactive mode to cancel queries at one or more backends (refs #36)
> Added option to cancel query in backend

- pgactivity/Data.py
Support to new version numbering strategy (X.Y - Major.Patch) starting for upcoming 10 version.
> Issue 64 add support to version 10

- pgactivity/Data.py
- pgactivity/UI.py
Effective for PostgreSQL v10 and more.
> Distinguish queries coming from BGW

- pg_activity
- pgactivity/Data.py
- pgactivity/UI.py
> Adding a active connections to summary.

- pg_activity
- pgactivity/Data.py
- pgactivity/Process.py
- pgactivity/UI.py
Added application_name as requested by #40
> Added application_name

- pg_activity
- pgactivity/Data.py
> Add PGSERVICE support

- pg_activity
> Try to reconnect to PostgreSQL cluster

- pgactivity/UI.py
> Do not try to display query duration if not there

- README.md
- pgactivity/UI.py
Increment size decreases to 0.5s when going below 1s
> Expand current 1-3s refresh interval to 0.5-5s

- pgactivity/UI.py
Help text now mirror 0.5-5s refresh range
> Minor help text adjustment for previous commit

- README.md
- setup.py
> Doc update and setup.py adjustment for psycopg2

- pgactivity/Data.py
> Fix duration mode

- RELEASE.md
Proposition for a HOWTO  dedicated to releases.
> RELEASE.md

- pg_activity
- setup.py
Bug fix:                                                                      
* Fix #139 : Fix duration mode for v11+
> Bump version to 1.6.1

- pg_activity
- setup.py
Bug fixes:
* Fix problems with versions of PostgreSQL older than 9.2. With this release of
PostgreSQL, the column state was added in pg_stat_activity. The column
current_query was also renamed to query. (fix: @blogh)
> Bump version to 1.6.2

- pgactivity/ui.py
- pgactivity/views.py
- pgactivity/widgets.py
- tests/test_ui.txt
- tests/test_views.txt
Changes concerning tests (no functional changes expected) to:
- limit mocks by running in non-local mode
- always use specified width for consistency
> tests improvements

- pg_activity
- pgactivity/data.py
- pgactivity/ui.py
- tests/test_ui.txt
We restore the previous behavior (sort of) that got dropped during ui rewrite by trying 3 times to reconnect in case of disconnection, waiting 5s between each attempts.
> Handle disconnection from postgres and try to reconnect

- pgactivity/data.py
This is available since psycopg2 version 2.5, which should be available
in most platforms.
> Use psycopg2's cursor as a context manager

- pgactivity/activities.py
- pgactivity/colors.py
- pgactivity/queries/__init__.py
- pgactivity/queries/get_blocking.sql
- pgactivity/queries/get_blocking_post_90200.sql
- pgactivity/queries/get_pg_activity.sql
- pgactivity/queries/get_pg_activity_post_100000.sql
- pgactivity/queries/get_pg_activity_post_110000.sql
- pgactivity/queries/get_pg_activity_post_90200.sql
- pgactivity/queries/get_pg_activity_post_90600.sql
- pgactivity/queries/get_waiting.sql
- pgactivity/queries/get_waiting_post_90200.sql
- pgactivity/types.py
- pgactivity/utils.py
- pgactivity/views.py
- tests/data/local-processes-input.json
- tests/test_views.txt
Follow-up on #171, cleaning some things while reading queries. (Read each commits for details.)
> Some cleanups and improvements to SQL queries

- pgactivity/data.py
Add tests for the version number detection, not that it's critical, but since I was reviewing the test thing ..
> Test versioncheck

- pg_activity
- pgactivity/data.py
Remove all the default values set in pg_activity to let libpq do it's thing.
> Cleanup defaults

- pgactivity/data.py
This got dropped in 9dff9464f8be680a9f57ea46067f13021e13ae93 by mistake. See also discussion at https://github.com/dalibo/pg_activity/pull/179#issuecomment-780677987.
> Restore logic to ask password on startup

- pg_activity
- pgactivity/data.py
- pgactivity/queries/disable_log_min_duration_sample.sql
- pgactivity/queries/disable_log_min_duration_statement.sql
- pgactivity/queries/set_application_name.sql
In response to : https://github.com/dalibo/pg_activity/issues/158
I have added application name and an option to disable query logging for pg_activity.
> Add appname and control logs (WIP)

- pg_activity
Though catch CTRL+C to abort the loop.
Fix #184
> Try to reconnect indefinitely

- setup.py
We follow recommendations from:
https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html
> Include queries data in sdist and installation

- pgactivity/data.py
I hit the error frequently and hate to receive a stack each time.
> Nicer error messages for dsn syntax errors

- pgactivity/types.py
- pgactivity/utils.py
> Handle 'pg_stat_activity.datname' column possibly being NULL

- pgactivity/handlers.py
- pgactivity/types.py
In Python 3.10, Enum's repr() no longer show the value
(https://bugs.python.org/issue40066).
Fix #205
> Update doctest for compat with Python 3.10a7

- pgactivity/__main__.py
- pgactivity/cli.py
Relates to issue: https://github.com/dalibo/pg_activity/issues/209
First time contributor - please let me know if I'm missing anything for this PR (I didn't see any contributing or dev guideline).
> Gracefully handle keyboard interupt (SIGINT)

- .github/workflows/tests.yml
- tests/conftest.py
- tests/test_data.py
- tests/test_ui.txt
Should make it easier to add regression tests for #149
> Add tests for the "data" module

- tests/test_data.py
This is the test for #224
Tested with the suite from 9.6 to 13.
Manual test on 9.4.
> Add tests for virtualxid locks

- pgactivity/queries/get_pg_activity.sql
> Add missing colum qualifier for dbname - leftover

- .github/workflows/publish.yml
- RELEASE.md
Cherry-picked from d8a175155d4415e44afd6243536096f6a8ac6a58.
> Add a github workflow to publish package to PyPI

- pgactivity/compat.py
- pgactivity/types.py
- tests/test_types.py
> compat for attr.fields_dict

- pgactivity/cli.py
* adds a stream logger gets info level messages and prints them when
we exit.
* adds a file logger gets all the messages and logs them to a file
specified by the new `--debug-file` option if available.
> Add logging to pgactivity

- docs/man/pg_activity.1
- docs/man/pg_activity.pod
- pgactivity/cli.py
> Add more information about what --rds and --filter do

- pgactivity/views.py
It used to be in green, then the color got dropped during header refactoring. Now using yellow, to make it less visible than more important information.
> Colorize the "duration mode"

- CHANGELOG.md
- README.md
- RELEASE.md
Let's keep a changelog in a file within the repository so that the information is more widely available that through github releases.
> Extract a change log file from Github releases

- CHANGELOG.md
- pgactivity/pg.py
> Prepare queries when using the Psycopg 3 database driver

- CHANGELOG.md
- pgactivity/data.py
- pgactivity/pg.py
- pgactivity/queries/get_blocking_oldest.sql
- pgactivity/queries/get_blocking_post_090200.sql
- pgactivity/queries/get_blocking_post_090600.sql
- pgactivity/queries/get_pg_activity_oldest.sql
- pgactivity/queries/get_pg_activity_post_090200.sql
- pgactivity/queries/get_pg_activity_post_090600.sql
- pgactivity/queries/get_pg_activity_post_100000.sql
- pgactivity/queries/get_pg_activity_post_110000.sql
- pgactivity/queries/get_pg_activity_post_130000.sql
- pgactivity/queries/get_waiting_oldest.sql
- pgactivity/queries/get_waiting_post_090200.sql
- pgactivity/types.py
- tests/test_data.py
Fix #332; fix #302 based on #344 and #343.
> Decode the "query" column on Python side

- CHANGELOG.md
- pgactivity/pg.py
- tests/test_data.py
Resolves part of #348, more specifically, the original problem statement not the one from https://github.com/dalibo/pg_activity/issues/348#issuecomment-1461039555 which will be addressed separately.
> improve handling of client encoding

- pgactivity/pg.py
Follow-up d91a36487d17df3997b6fd202ae4d2917dded688
> Preserve PGCLIENTENCODING before setting client_encoding=auto

- CHANGELOG.md
- README.md
- pgactivity/cli.py
- pgactivity/config.py
- pgactivity/types.py
- pgactivity/ui.py
- tests/test_config.py
- tests/test_ui.txt
This is an alternative to #370 which adds support for configuring pg_activity from a file. ~~The JSON format is to be discussed.~~ (EDIT: changed to INI)
What do you think @blogh?
> add a configuration to control columns visibility and width

- CHANGELOG.md
- pgactivity/data.py
- pgactivity/queries/get_server_info_oldest.sql
- pgactivity/queries/get_server_info_post_090100.sql
- pgactivity/queries/get_server_info_post_090200.sql
- pgactivity/queries/get_server_info_post_090400.sql
- pgactivity/queries/get_server_info_post_090600.sql
- pgactivity/queries/get_server_info_post_100000.sql
- pgactivity/queries/get_server_info_post_110000.sql
- pgactivity/types.py
- pgactivity/views.py
- tests/test_ui.txt
- tests/test_views.txt
To the global / instance info section. To quickly understand if something wrong with queries
> Add a new output column "rollback ratio"

- .pre-commit-config.yaml
- CHANGELOG.md
- MANIFEST.in
- README.md
- pyproject.toml
> document how to hack on pg_activity

- CHANGELOG.md
- docs/man/pg_activity.1
- docs/man/pg_activity.pod
- pgactivity/pg.py
- pgactivity/views.py
- tests/test_ui.txt
- tests/test_views.txt
Fix https://github.com/dalibo/pg_activity/issues/398
> Rephrase help text for K action

- .github/workflows/tests.yml
> Run tests with Python 3.12

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- pgactivity/activities.py
- pgactivity/cli.py
- pgactivity/compat.py
- pgactivity/config.py
- pgactivity/data.py
- pgactivity/handlers.py
- pgactivity/keys.py
- pgactivity/pg.py
- pgactivity/types.py
- pgactivity/ui.py
- pgactivity/utils.py
- pgactivity/views.py
- pgactivity/widgets.py
- pyproject.toml
- tests/conftest.py
- tests/test_config.py
- tests/test_data.py
- tox.ini
> Upgrade type annotations syntax

- CHANGELOG.md
- MANIFEST.in
- README.md
- docs/man/pg_activity.1
- docs/man/pg_activity.pod
- pgactivity/cli.py
- pgactivity/compat.py
- pgactivity/config.py
- pgactivity/profiles/minimal.conf
- pgactivity/profiles/narrow.conf
- pgactivity/profiles/wide.conf
- tests/test_config.py
implements the idea suggested in https://github.com/dalibo/pg_activity/pull/387#issuecomment-1623178466
> add builtin profiles

- CHANGELOG.md
- pgactivity/utils.py
> fix datetime deprecation warning

- CHANGELOG.md
- pgactivity/cli.py
This seems to be what most interactive programs do.
> Exit 0 upon keyboard interrupt
